<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/19 16:49:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=proba',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
